# .github/workflows/gh-pages.yml
name: Build & Deploy to GitHub Pages
on:
  push:
    branches:
      - main # or your default

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1) Create the env.js file from your secret
      - name: Generate env.js
        run: |
          echo "export const API_KEY = '${{ secrets.MAPBOX_TOKEN }}';" \
            > ./public/env.js

      # 2) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # or wherever your built site lives
